import type { FastifyInstance } from "fastify";
import { serviceDb } from "../lib/supabase.js";
import { getErrorMessage } from "../lib/errors.js";

/**
 * Capability-token routes. These are opened by people with no FLOAT account,
 * from a link someone sent them, so they cannot carry a session.
 *
 * Authorization is the token itself: a random column value generated by
 * Postgres. Lookups run service-side by exact token match and return only the
 * fields that link is entitled to see — never the whole row, and never
 * anything belonging to another user.
 */
export function registerLinkRoutes(app: FastifyInstance) {
  /** Split settle link. */
  app.get<{ Params: { token: string } }>("/settle/:token", async (req, reply) => {
    const db = serviceDb();
    const { data, error } = await db
      .from("splits")
      .select("id, name, total_amount, token, status, organizer_id, split_members(id, member_ref, share_amount, settled)")
      .eq("share_link_token", req.params.token)
      .maybeSingle();

    if (error || !data) {
      return reply.code(404).send({ error: "This link is no longer valid." });
    }

    // Members settle by paying the organizer directly, so the link has to
    // carry their address. Nothing else about the organizer is exposed.
    const { data: organizer } = await db
      .from("users")
      .select("address, handle")
      .eq("id", data.organizer_id)
      .maybeSingle();

    const { organizer_id: _omitted, ...split } = data;
    return {
      ...split,
      organizerAddress: organizer?.address ?? null,
      organizerHandle: organizer?.handle ?? null,
    };
  });

  /** Marks one member settled. Requires the tx hash so the DB never claims a
   *  settlement the chain has not seen. */
  app.post<{ Params: { token: string }; Body: { memberId: string; txHash: string } }>(
    "/settle/:token",
    async (req, reply) => {
      const { memberId, txHash } = req.body ?? ({} as never);
      if (!memberId || !/^0x[a-fA-F0-9]+$/.test(txHash ?? "")) {
        return reply.code(400).send({ error: "memberId and txHash are required." });
      }

      const db = serviceDb();
      const { data: split } = await db
        .from("splits")
        .select("id")
        .eq("share_link_token", req.params.token)
        .maybeSingle();
      if (!split) return reply.code(404).send({ error: "This link is no longer valid." });

      // Scoped to this split, so a leaked token cannot settle someone else's.
      const { data, error } = await db
        .from("split_members")
        .update({ settled: true, settle_tx_hash: txHash, settled_at: new Date().toISOString() })
        .eq("id", memberId)
        .eq("split_id", split.id)
        .select()
        .single();
      if (error) return reply.code(400).send({ error: getErrorMessage(error) });

      // Close the split once everyone has paid.
      const { data: remaining } = await db
        .from("split_members")
        .select("id")
        .eq("split_id", split.id)
        .eq("settled", false);
      if ((remaining?.length ?? 0) === 0) {
        await db.from("splits").update({ status: "settled" }).eq("id", split.id);
      }

      return data;
    }
  );

  /**
   * Claim view for a send to someone with no FLOAT account. The claim token is
   * generated per send; the sender's identity is not exposed beyond a handle.
   */
  app.get<{ Params: { token: string } }>("/claim/:token", async (req, reply) => {
    const db = serviceDb();
    const { data, error } = await db
      .from("sends")
      .select("id, amount, token, note, status, claimed_at, recipient_input, sender_id")
      .eq("claim_token", req.params.token)
      .maybeSingle();

    if (error || !data) {
      return reply.code(404).send({ error: "This link is no longer valid." });
    }

    const { data: sender } = await db
      .from("users")
      .select("handle, address")
      .eq("id", data.sender_id)
      .maybeSingle();

    const { sender_id: _omitted, ...send } = data;
    return { ...send, senderHandle: sender?.handle ?? null };
  });

  /**
   * Shareable receipt for a completed send.
   *
   * Replaces linking receipts out to Particle's explorer, which showed a
   * bundler's view of a userOp rather than "you paid this person this much"
   * and exposed the sender's whole activity history to anyone with the link.
   *
   * Keyed on share_token, not the send id, so a shared receipt can be revoked
   * without touching the send. Returns only what a receipt shows — no
   * addresses, no claim token, nothing about the sender beyond their handle.
   */
  app.get<{ Params: { token: string } }>("/receipt/:token", async (req, reply) => {
    const db = serviceDb();
    const { data, error } = await db
      .from("sends")
      .select("amount, token, note, status, recipient_input, recipient_type, tx_hash, created_at, sender_id")
      .eq("share_token", req.params.token)
      .maybeSingle();

    if (error || !data) {
      return reply.code(404).send({ error: "This receipt is no longer available." });
    }

    const { data: sender } = await db
      .from("users")
      .select("handle, avatar_url")
      .eq("id", data.sender_id)
      .maybeSingle();

    const { sender_id: _omitted, ...receipt } = data;
    return {
      ...receipt,
      senderHandle: sender?.handle ?? null,
      senderAvatarUrl: sender?.avatar_url ?? null,
    };
  });

  /** Marks a send claimed once the recipient has a wallet. */
  app.post<{ Params: { token: string }; Body: { address: string } }>(
    "/claim/:token",
    async (req, reply) => {
      const address = req.body?.address;
      if (!address || !/^0x[a-fA-F0-9]{40}$/.test(address)) {
        return reply.code(400).send({ error: "A wallet address is required." });
      }

      const db = serviceDb();
      const { data: send } = await db
        .from("sends")
        .select("id, claimed_at")
        .eq("claim_token", req.params.token)
        .maybeSingle();
      if (!send) return reply.code(404).send({ error: "This link is no longer valid." });
      if (send.claimed_at) {
        return reply.code(409).send({ error: "This was already claimed." });
      }

      const { data, error } = await db
        .from("sends")
        .update({
          recipient_address: address.toLowerCase(),
          claimed_at: new Date().toISOString(),
        })
        .eq("id", send.id)
        .select("id, amount, token, claimed_at")
        .single();
      if (error) return reply.code(400).send({ error: getErrorMessage(error) });

      return data;
    }
  );

  /** Public pledge, for the shareable accountability card. */
  app.get<{ Params: { id: string } }>("/pledge/:id", async (req, reply) => {
    const db = serviceDb();
    const { data, error } = await db
      .from("pledges")
      .select("id, goal, stake_amount, token, deadline_unix, status, failure_destination_label, is_public, pledger_id")
      .eq("id", req.params.id)
      .maybeSingle();

    if (error || !data || !data.is_public) {
      return reply.code(404).send({ error: "This pledge isn't public." });
    }

    const { data: pledger } = await db
      .from("users")
      .select("handle")
      .eq("id", data.pledger_id)
      .maybeSingle();

    const { pledger_id: _omitted, ...pledge } = data;
    return { ...pledge, pledgerHandle: pledger?.handle ?? null };
  });

  /** Leash beneficiary claim view. */
  app.get<{ Params: { token: string } }>("/leash/claim/:token", async (req, reply) => {
    const { data, error } = await serviceDb()
      .from("leashes")
      .select("id, beneficiary_ref, token, spend_limit, spent, expiry_unix, expiry_tz, revoked, allowed_contracts, contract_scope, onchain_leash_id")
      .eq("claim_token", req.params.token)
      .maybeSingle();

    if (error || !data) {
      return reply.code(404).send({ error: "This link is no longer valid." });
    }
    if (data.revoked) {
      return reply.code(410).send({ error: "Access was removed.", revoked: true });
    }
    return { ...data, remaining: Math.max(0, data.spend_limit - data.spent) };
  });

  /** Witness view of a pledge. */
  app.get<{ Params: { token: string } }>("/witness/:token", async (req, reply) => {
    const { data, error } = await serviceDb()
      .from("pledges")
      .select("id, goal, stake_amount, token, deadline_unix, deadline_tz, status, failure_destination_label, onchain_pledge_id")
      .eq("witness_token", req.params.token)
      .maybeSingle();

    if (error || !data) {
      return reply.code(404).send({ error: "This link is no longer valid." });
    }
    return data;
  });

  /**
   * Witness verdict. This is the only path that can trigger a slash, so the
   * on-chain call is made by the witness in their browser and the hash is
   * required here — the API records the outcome, it never decides it.
   */
  app.post<{ Params: { token: string }; Body: { verdict: "success" | "failure"; txHash: string } }>(
    "/witness/:token",
    async (req, reply) => {
      const { verdict, txHash } = req.body ?? ({} as never);
      if (verdict !== "success" && verdict !== "failure") {
        return reply.code(400).send({ error: "verdict must be success or failure." });
      }
      if (!/^0x[a-fA-F0-9]+$/.test(txHash ?? "")) {
        return reply.code(400).send({ error: "txHash is required." });
      }

      const db = serviceDb();
      const { data: pledge } = await db
        .from("pledges")
        .select("id, status")
        .eq("witness_token", req.params.token)
        .maybeSingle();
      if (!pledge) return reply.code(404).send({ error: "This link is no longer valid." });
      if (pledge.status !== "locked") {
        return reply.code(409).send({ error: "This pledge was already resolved." });
      }

      const { data, error } = await db
        .from("pledges")
        .update({
          status: verdict === "success" ? "succeeded" : "failed",
          resolved_at: new Date().toISOString(),
        })
        .eq("id", pledge.id)
        .select()
        .single();
      if (error) return reply.code(400).send({ error: getErrorMessage(error) });

      await db.from("pledge_events").insert({
        pledge_id: pledge.id,
        event_type: verdict === "success" ? "witness_confirmed_success" : "witness_confirmed_failure",
        tx_hash: txHash,
      });

      return data;
    }
  );
}
