import type { Hono, Env } from "hono";
import { serviceDb } from "../lib/supabase.js";
import { getErrorMessage } from "../lib/errors.js";
import { findSettleTransfer } from "../lib/settle-verify.js";

/**
 * Capability-token routes. These are opened by people with no FLOAT account,
 * from a link someone sent them, so they cannot carry a session.
 *
 * Authorization is the token itself: a random column value generated by
 * Postgres. Lookups run service-side by exact token match and return only the
 * fields that link is entitled to see — never the whole row, and never
 * anything belonging to another user.
 */
export function registerLinkRoutes<E extends Env>(app: Hono<E>) {
  /** Split settle link. */
  app.get("/settle/:token", async (c) => {
    const db = serviceDb();
    const { data, error } = await db
      .from("splits")
      .select("id, name, total_amount, token, status, organizer_id, split_members(id, member_ref, share_amount, settled)")
      .eq("share_link_token", c.req.param("token"))
      .maybeSingle();

    if (error || !data) {
      return c.json({ error: "This link is no longer valid." }, 404);
    }

    // Members settle by paying the organizer directly, so the link has to
    // carry their address. Nothing else about the organizer is exposed.
    const { data: organizer } = await db
      .from("users")
      .select("address, handle")
      .eq("id", data.organizer_id)
      .maybeSingle();

    const { organizer_id: _omitted, ...split } = data;
    return c.json({
      ...split,
      organizerAddress: organizer?.address ?? null,
      organizerHandle: organizer?.handle ?? null,
    });
  });

  /**
   * Marks one member settled — but only once the chain corroborates it. The
   * client's identifier is Particle's routing id, which no RPC can look up,
   * so the proof is a USDC Transfer log to the organizer for the share; the
   * hash recorded is the one found on-chain, never the one the client sent.
   */
  app.post("/settle/:token", async (c) => {
    const body = (await c.req.json().catch(() => ({}))) as {
      memberId?: string;
      txHash?: string;
    };
    const { memberId, txHash } = body;
    if (!memberId || !/^0x[a-fA-F0-9]+$/.test(txHash ?? "")) {
      return c.json({ error: "memberId and txHash are required." }, 400);
    }

    const db = serviceDb();
    const { data: split } = await db
      .from("splits")
      .select("id, organizer_id, split_members(id, share_amount, settled, settle_tx_hash)")
      .eq("share_link_token", c.req.param("token"))
      .maybeSingle();
    if (!split) return c.json({ error: "This link is no longer valid." }, 404);

    const member = split.split_members.find((m) => m.id === memberId);
    if (!member) return c.json({ error: "That member isn't part of this split." }, 404);

    // A record retry after success is a no-op, not an error: the money
    // moved once and the row already says so.
    if (member.settled) {
      const { data: row } = await db
        .from("split_members")
        .select()
        .eq("id", memberId)
        .single();
      return c.json(row);
    }

    const { data: organizer } = await db
      .from("users")
      .select("address")
      .eq("id", split.organizer_id)
      .maybeSingle();
    if (!organizer?.address) {
      return c.json({ error: "The organizer has no address to verify against." }, 409);
    }

    // Each found hash settles at most one share of this split.
    const usedHashes = new Set(
      split.split_members
        .map((m) => m.settle_tx_hash?.toLowerCase())
        .filter((h): h is string => !!h)
    );
    const proof = await findSettleTransfer({
      organizer: organizer.address as `0x${string}`,
      amountUsd: member.share_amount,
      excludeTxHashes: usedHashes,
    });
    if (!proof) {
      return c.json(
        { error: "The transfer hasn't been seen on-chain yet.", retryable: true },
        409
      );
    }

    // Scoped to this split, so a leaked token cannot settle someone else's.
    const { data, error } = await db
      .from("split_members")
      .update({
        settled: true,
        settle_tx_hash: proof.txHash,
        settled_at: new Date().toISOString(),
      })
      .eq("id", memberId)
      .eq("split_id", split.id)
      .select()
      .single();
    if (error) return c.json({ error: getErrorMessage(error) }, 400);

    // The organizer's feed and bell learn about it the moment the verified
    // settle records — written here because this is the only place a
    // settlement becomes true. Failures log; the settle itself stands.
    const { error: activityError } = await db.from("activity").insert({
      user_id: split.organizer_id,
      type: "split_member_settled",
      ref_type: "split",
      ref_id: split.id,
    });
    if (activityError) console.error("activity insert failed", activityError.message);
    await db.from("notifications").insert({
      user_id: split.organizer_id,
      type: "split_member_settled",
      payload: { amount: member.share_amount, txHash: proof.txHash },
    });

    // Close the split once everyone has paid.
    const { data: remaining } = await db
      .from("split_members")
      .select("id")
      .eq("split_id", split.id)
      .eq("settled", false);
    if ((remaining?.length ?? 0) === 0) {
      await db.from("splits").update({ status: "settled" }).eq("id", split.id);
      const { error: settledError } = await db.from("activity").insert({
        user_id: split.organizer_id,
        type: "split_settled",
        ref_type: "split",
        ref_id: split.id,
      });
      if (settledError) console.error("activity insert failed", settledError.message);
    }

    return c.json(data);
  });

  /**
   * Claim view for a send to someone with no FLOAT account. The claim token is
   * generated per send; the sender's identity is not exposed beyond a handle.
   */
  app.get("/claim/:token", async (c) => {
    const db = serviceDb();
    const { data, error } = await db
      .from("sends")
      .select("id, amount, token, note, status, claimed_at, recipient_input, sender_id")
      .eq("claim_token", c.req.param("token"))
      .maybeSingle();

    if (error || !data) {
      return c.json({ error: "This link is no longer valid." }, 404);
    }

    const { data: sender } = await db
      .from("users")
      .select("handle, address")
      .eq("id", data.sender_id)
      .maybeSingle();

    const { sender_id: _omitted, ...send } = data;
    return c.json({ ...send, senderHandle: sender?.handle ?? null });
  });

  /**
   * Shareable receipt for a completed send.
   *
   * Replaces linking receipts out to Particle's explorer, which showed a
   * bundler's view of a userOp rather than "you paid this person this much"
   * and exposed the sender's whole activity history to anyone with the link.
   *
   * Keyed on share_token, not the send id, so a shared receipt can be revoked
   * without touching the send. Returns only what a receipt shows — no
   * addresses, no claim token, nothing about the sender beyond their handle.
   */
  app.get("/receipt/:token", async (c) => {
    const db = serviceDb();
    const { data, error } = await db
      .from("sends")
      .select("amount, token, note, status, recipient_input, recipient_type, tx_hash, created_at, sender_id")
      .eq("share_token", c.req.param("token"))
      .maybeSingle();

    if (error || !data) {
      return c.json({ error: "This receipt is no longer available." }, 404);
    }

    const { data: sender } = await db
      .from("users")
      .select("handle, avatar_url")
      .eq("id", data.sender_id)
      .maybeSingle();

    const { sender_id: _omitted, ...receipt } = data;
    return c.json({
      ...receipt,
      senderHandle: sender?.handle ?? null,
      senderAvatarUrl: sender?.avatar_url ?? null,
    });
  });

  /** Marks a send claimed once the recipient has a wallet. */
  app.post("/claim/:token", async (c) => {
    const body = (await c.req.json().catch(() => ({}))) as { address?: string };
    const address = body.address;
    if (!address || !/^0x[a-fA-F0-9]{40}$/.test(address)) {
      return c.json({ error: "A wallet address is required." }, 400);
    }

    const db = serviceDb();
    const { data: send } = await db
      .from("sends")
      .select("id, claimed_at")
      .eq("claim_token", c.req.param("token"))
      .maybeSingle();
    if (!send) return c.json({ error: "This link is no longer valid." }, 404);
    if (send.claimed_at) {
      return c.json({ error: "This was already claimed." }, 409);
    }

    const { data, error } = await db
      .from("sends")
      .update({
        recipient_address: address.toLowerCase(),
        claimed_at: new Date().toISOString(),
      })
      .eq("id", send.id)
      .select("id, amount, token, claimed_at")
      .single();
    if (error) return c.json({ error: getErrorMessage(error) }, 400);

    return c.json(data);
  });

  /** Public pledge, for the shareable accountability card. */
  app.get("/pledge/:id", async (c) => {
    const db = serviceDb();
    const { data, error } = await db
      .from("pledges")
      .select("id, goal, stake_amount, token, deadline_unix, status, failure_destination_label, is_public, pledger_id")
      .eq("id", c.req.param("id"))
      .maybeSingle();

    if (error || !data || !data.is_public) {
      return c.json({ error: "This pledge isn't public." }, 404);
    }

    const { data: pledger } = await db
      .from("users")
      .select("handle")
      .eq("id", data.pledger_id)
      .maybeSingle();

    const { pledger_id: _omitted, ...pledge } = data;
    return c.json({ ...pledge, pledgerHandle: pledger?.handle ?? null });
  });

  /** Leash beneficiary claim view. */
  app.get("/leash/claim/:token", async (c) => {
    const { data, error } = await serviceDb()
      .from("leashes")
      .select("id, beneficiary_ref, token, spend_limit, spent, expiry_unix, expiry_tz, revoked, onchain_leash_id")
      .eq("claim_token", c.req.param("token"))
      .maybeSingle();

    if (error || !data) {
      return c.json({ error: "This link is no longer valid." }, 404);
    }
    if (data.revoked) {
      return c.json({ error: "Access was removed.", revoked: true }, 410);
    }
    return c.json({ ...data, remaining: Math.max(0, data.spend_limit - data.spent) });
  });

  /** Witness view of a pledge. */
  app.get("/witness/:token", async (c) => {
    const { data, error } = await serviceDb()
      .from("pledges")
      .select("id, goal, stake_amount, token, deadline_unix, deadline_tz, status, failure_destination_label, onchain_pledge_id")
      .eq("witness_token", c.req.param("token"))
      .maybeSingle();

    if (error || !data) {
      return c.json({ error: "This link is no longer valid." }, 404);
    }
    return c.json(data);
  });

  /**
   * Witness verdict. This is the only path that can trigger a slash, so the
   * on-chain call is made by the witness in their browser and the hash is
   * required here — the API records the outcome, it never decides it.
   */
  app.post("/witness/:token", async (c) => {
    const body = (await c.req.json().catch(() => ({}))) as {
      verdict?: "success" | "failure";
      txHash?: string;
    };
    const { verdict, txHash } = body;
    if (verdict !== "success" && verdict !== "failure") {
      return c.json({ error: "verdict must be success or failure." }, 400);
    }
    if (!/^0x[a-fA-F0-9]+$/.test(txHash ?? "")) {
      return c.json({ error: "txHash is required." }, 400);
    }

    const db = serviceDb();
    const { data: pledge } = await db
      .from("pledges")
      .select("id, status")
      .eq("witness_token", c.req.param("token"))
      .maybeSingle();
    if (!pledge) return c.json({ error: "This link is no longer valid." }, 404);
    if (pledge.status !== "locked") {
      return c.json({ error: "This pledge was already resolved." }, 409);
    }

    const { data, error } = await db
      .from("pledges")
      .update({
        status: verdict === "success" ? "succeeded" : "failed",
        resolved_at: new Date().toISOString(),
      })
      .eq("id", pledge.id)
      .select()
      .single();
    if (error) return c.json({ error: getErrorMessage(error) }, 400);

    await db.from("pledge_events").insert({
      pledge_id: pledge.id,
      event_type: verdict === "success" ? "witness_confirmed_success" : "witness_confirmed_failure",
      tx_hash: txHash,
    });

    return c.json(data);
  });
}
